import type { DecisionCategory } from "../domain/canonical.ts";
import type { DecisionThinkingProfile, ThinkingDimension } from "./decision-thinking-profile.ts";

export type DecisionAxis = "financial"|"customer"|"market"|"people"|"stakeholders"|"execution"|"evidence"|"risk"|"reversibility"|"opportunityCost"|"inaction"|"legal"|"reputation"|"longTerm"|"dissent";

export interface ExtractedPastDecision { title:string; context:string; choice:string; rationale:string; outcome:string; category:DecisionCategory; presentAxes:DecisionAxis[]; absentAxes:DecisionAxis[] }
export interface DecisionAxisDefinition { axis:DecisionAxis; label:string; importance:1|2|3; question:string }
export interface BlindSpot { axis:DecisionAxis; label:string; score:number; reason:string; question:string }
export type FeedbackKind="useful"|"already_considered"|"more_important"|"less_important"|"incorrect"|"changed_decision";
export interface ComplementFeedback { axis:DecisionAxis; kind:FeedbackKind; createdAt:string }
export interface DecisionComplementReport { alreadyCovered:DecisionAxisDefinition[]; complements:BlindSpot[]; contraryPerspective:string; decisiveQuestion:string; nextCheck:string }
export interface OutcomeFollowUp { days:30|60|90; dueAt:string; questions:string[] }
export function serializeComplementFeedback(feedback:ComplementFeedback):string{return JSON.stringify(feedback);}
export function parseComplementFeedback(raw:string):ComplementFeedback|null{try{const value=JSON.parse(raw) as Partial<ComplementFeedback>;const axes=Object.keys(axisPatterns) as DecisionAxis[];const kinds:FeedbackKind[]=["useful","already_considered","more_important","less_important","incorrect","changed_decision"];return axes.includes(value.axis as DecisionAxis)&&kinds.includes(value.kind as FeedbackKind)&&typeof value.createdAt==="string"?value as ComplementFeedback:null;}catch{return null;}}

const axisPatterns:Record<DecisionAxis,RegExp>={
  financial:/coût|budget|marge|revenu|rentab|prix|€|roi/i,customer:/client|usage|adoption|churn|besoin/i,market:/marché|concurr|segment|demande/i,people:/équipe|salari|collabor|talent|compétence/i,stakeholders:/partie prenante|direction|adhésion|sponsor|partenaire/i,execution:/exécut|capacité|temps|ressource|livr|planning/i,evidence:/preuve|donnée|test|pilote|source|mesure/i,risk:/risque|incertain|menace|exposition/i,reversibility:/réversib|retour arrière|sortie|annul|rollback/i,opportunityCost:/renonc|report|coût d.opportunité|à la place/i,inaction:/statu quo|inaction|ne rien faire|attendre/i,legal:/jurid|droit|contrat|réglement|conform/i,reputation:/réputation|image|marque|confiance/i,longTerm:/long terme|durable|dans un an|péren/i,dissent:/contre|objection|désaccord|alternative|contradic/i
};

const common:DecisionAxisDefinition[]=[
  {axis:"opportunityCost",label:"Coût d’opportunité",importance:3,question:"À quoi faudra-t-il renoncer si cette option est retenue ?"},
  {axis:"reversibility",label:"Réversibilité",importance:3,question:"Jusqu’à quel point cette décision peut-elle être annulée sans dommage majeur ?"},
  {axis:"inaction",label:"Coût de l’inaction",importance:2,question:"Que se passe-t-il concrètement si aucune décision n’est prise maintenant ?"},
  {axis:"dissent",label:"Perspective contraire",importance:2,question:"Quel est le meilleur argument contre l’option actuellement préférée ?"},
];

export const decisionAxisMatrices:Record<DecisionCategory,DecisionAxisDefinition[]>={
  investment:[{axis:"financial",label:"Rendement et exposition",importance:3,question:"Quel rendement ajusté du risque justifie l’immobilisation des ressources ?"},{axis:"market",label:"Dynamique de marché",importance:2,question:"Quelle évolution du marché invaliderait la thèse ?"},{axis:"risk",label:"Risque de perte",importance:3,question:"Quelle perte maximale est acceptable ?"},{axis:"evidence",label:"Preuves externes",importance:3,question:"Quelle preuve indépendante soutient les hypothèses principales ?"},...common],
  hiring:[{axis:"people",label:"Effet sur l’équipe",importance:3,question:"Quelle capacité manque réellement à l’équipe actuelle ?"},{axis:"financial",label:"Coût complet",importance:3,question:"Quel est le coût complet jusqu’à l’autonomie du recrutement ?"},{axis:"execution",label:"Capacité d’intégration",importance:2,question:"Qui rendra cette personne opérationnelle et en combien de temps ?"},{axis:"evidence",label:"Preuve de besoin",importance:3,question:"Quel résultat démontre qu’un recrutement est préférable à une autre solution ?"},...common],
  pricing:[{axis:"customer",label:"Valeur perçue",importance:3,question:"Quelle valeur mesurable le client associe-t-il à l’offre ?"},{axis:"financial",label:"Marge et revenu",importance:3,question:"Quel effet net sur la marge et le revenu récurrent ?"},{axis:"market",label:"Réaction concurrentielle",importance:2,question:"Comment les alternatives du marché modifient-elles l’acceptabilité du prix ?"},{axis:"execution",label:"Exécution commerciale",importance:2,question:"L’équipe sait-elle expliquer et défendre ce prix ?"},...common],
  partnership:[{axis:"stakeholders",label:"Gouvernance",importance:3,question:"Qui arbitre en cas de désaccord ?"},{axis:"reputation",label:"Risque réputationnel",importance:2,question:"Que deviendra votre réputation si le partenaire échoue ?"},{axis:"legal",label:"Dépendances contractuelles",importance:3,question:"Quelles obligations survivront à la fin du partenariat ?"},{axis:"execution",label:"Capacité conjointe",importance:2,question:"Quelles ressources chaque partie protège-t-elle réellement ?"},...common],
  launch:[{axis:"customer",label:"Problème client",importance:3,question:"Quelle preuve montre que le problème mérite un changement de comportement ?"},{axis:"market",label:"Distribution",importance:3,question:"Comment les premiers utilisateurs découvriront-ils l’offre ?"},{axis:"execution",label:"Capacité à livrer",importance:3,question:"Quelle promesse peut être tenue avec les moyens disponibles ?"},{axis:"evidence",label:"Signal d’adoption",importance:3,question:"Quel comportement mesurable prouvera l’adoption ?"},...common],
  workforce_restructuring:[{axis:"people",label:"Conséquences humaines",importance:3,question:"Quelles populations et compétences critiques seront affectées ?"},{axis:"legal",label:"Cadre juridique",importance:3,question:"Quelles obligations encadrent le calendrier et les options ?"},{axis:"execution",label:"Continuité opérationnelle",importance:3,question:"Comment maintenir les opérations pendant la transition ?"},{axis:"reputation",label:"Confiance",importance:3,question:"Quels effets sur la confiance interne et externe ?"},...common],
  generic:[{axis:"financial",label:"Effet économique",importance:2,question:"Quel effet économique direct et indirect est attendu ?"},{axis:"customer",label:"Impact client",importance:2,question:"Quel changement concret cette décision produit-elle pour le client ?"},{axis:"people",label:"Impact humain",importance:2,question:"Qui supportera l’essentiel des conséquences ?"},{axis:"execution",label:"Capacité d’exécution",importance:3,question:"Quelles ressources sont réellement disponibles ?"},{axis:"risk",label:"Risques",importance:3,question:"Quel scénario défavorable mérite une protection ?"},...common],
};

export function classifyDecisionCategory(text:string):DecisionCategory{if(/recrut|embauch|candidat|poste/i.test(text))return"hiring";if(/invest|acqui|participation|capital/i.test(text))return"investment";if(/prix|pricing|tarif|marge/i.test(text))return"pricing";if(/parten|alliance|joint.?venture/i.test(text))return"partnership";if(/lanc|produit|offre|mise sur le marché/i.test(text))return"launch";if(/restruct|effectif|licenci|réorgan/i.test(text))return"workforce_restructuring";return"generic";}
export function detectDecisionAxes(text:string):DecisionAxis[]{return(Object.keys(axisPatterns) as DecisionAxis[]).filter((axis)=>axisPatterns[axis].test(text));}

export function extractPastDecisions(text:string,limit=5):ExtractedPastDecision[]{
  const blocks=text.split(/\n\s*\n|\n(?=(?:décision|decision|situation)\s*[:#-])/i).map((block)=>block.trim()).filter((block)=>block.length>=25).slice(0,Math.max(1,Math.min(5,limit)));
  return blocks.map((block,index)=>{const lines=block.split("\n").map((line)=>line.trim()).filter(Boolean);const category=classifyDecisionCategory(block);const presentAxes=detectDecisionAxes(block);const matrix=decisionAxisMatrices[category];return{title:(lines[0]??`Décision ${index+1}`).replace(/^(décision|decision|situation)\s*[:#-]?\s*/i,"").slice(0,100),context:block,choice:(block.match(/(?:choix|décision finale|retenu)\s*[:=-]\s*([^\n.]+)/i)?.[1]??"À confirmer").trim(),rationale:(block.match(/(?:pourquoi|raison|car)\s*[:=-]?\s*([^\n]+)/i)?.[1]??"Raisons à confirmer").trim(),outcome:(block.match(/(?:résultat|outcome)\s*[:=-]\s*([^\n]+)/i)?.[1]??"Résultat à renseigner").trim(),category,presentAxes,absentAxes:matrix.filter((item)=>!presentAxes.includes(item.axis)).map((item)=>item.axis)};});
}

const dimensionAxis:Partial<Record<ThinkingDimension,DecisionAxis>>={evidence:"evidence",risk:"risk",stakeholders:"stakeholders",execution:"execution",opportunityCost:"opportunityCost",reversibility:"reversibility",longTerm:"longTerm",dissent:"dissent"};

export function rankBlindSpots(input:{text:string;category?:DecisionCategory;profile?:DecisionThinkingProfile;feedback?:ComplementFeedback[];limit?:number}):BlindSpot[]{
  const category=input.category??classifyDecisionCategory(input.text);const present=detectDecisionAxes(input.text);const feedback=input.feedback??[];
  return decisionAxisMatrices[category].filter((item)=>!present.includes(item.axis)).map((item)=>{const dimension=Object.entries(dimensionAxis).find(([,axis])=>axis===item.axis)?.[0] as ThinkingDimension|undefined;const mastery=dimension&&input.profile?input.profile.dimensions[dimension]:50;const corrections=feedback.filter((entry)=>entry.axis===item.axis);const adjustment=corrections.reduce((sum,entry)=>sum+({useful:10,changed_decision:18,more_important:14,already_considered:-18,less_important:-12,incorrect:-20}[entry.kind]),0);const score=Math.max(0,Math.min(100,item.importance*24+(100-mastery)*.32+adjustment));return{axis:item.axis,label:item.label,score:Math.round(score),reason:`Cet axe est absent du dossier et compte ${item.importance===3?"fortement":"sensiblement"} pour une décision de type ${category}.`,question:item.question};}).sort((a,b)=>b.score-a.score).slice(0,input.limit??3);
}

export function buildComplementReport(input:{text:string;category?:DecisionCategory;profile?:DecisionThinkingProfile;feedback?:ComplementFeedback[]}):DecisionComplementReport{
  const category=input.category??classifyDecisionCategory(input.text);const present=detectDecisionAxes(input.text);const matrix=decisionAxisMatrices[category];const complements=rankBlindSpots({...input,category,limit:3});
  return{alreadyCovered:matrix.filter((item)=>present.includes(item.axis)).slice(0,3),complements,contraryPerspective:complements.find((item)=>item.axis==="dissent")?.question??"Dans quelles conditions l’option opposée deviendrait-elle préférable ?",decisiveQuestion:complements[0]?.question??"Quelle information pourrait réellement changer votre décision ?",nextCheck:complements[0]?`Obtenir une preuve sur « ${complements[0].label} » avant tout engagement irréversible.`:"Vérifier une hypothèse critique avec une source indépendante."};
}

export function applyProfileFeedback(profile:DecisionThinkingProfile,feedback:ComplementFeedback[]):DecisionThinkingProfile{
  const dimensions={...profile.dimensions};for(const item of feedback){const dimension=Object.entries(dimensionAxis).find(([,axis])=>axis===item.axis)?.[0] as ThinkingDimension|undefined;if(!dimension)continue;const delta=({useful:-4,changed_decision:-6,more_important:-3,already_considered:6,less_important:2,incorrect:4}[item.kind]);dimensions[dimension]=Math.max(0,Math.min(100,dimensions[dimension]+delta));}
  const evidenceCount=profile.evidenceCount+feedback.length;const confidence:DecisionThinkingProfile["confidence"]=evidenceCount>=30?"established":evidenceCount>=18?"supported":evidenceCount>=12?"emerging":"initial";return{...profile,dimensions,evidenceCount,confidence,source:"corrected"};
}

export function scheduleOutcomeFollowUps(decidedAt:string):OutcomeFollowUp[]{const base=new Date(decidedAt);return([30,60,90] as const).map((days)=>{const due=new Date(base);due.setUTCDate(due.getUTCDate()+days);return{days,dueAt:due.toISOString(),questions:["La décision a-t-elle été exécutée ?","Quel résultat mesurable a été obtenu ?","Quel critère s’est révélé déterminant ?","Quel risque ou axe négligé s’est matérialisé ?"]};});}
