import type { CognitiveCase } from "../domain/canonical.ts";

export type StrategyStudyId = "market"|"competition"|"personas"|"trends"|"swot"|"pricing"|"gtm"|"journey"|"economics"|"synthesis";
export type StrategyPillar = "Marché"|"Client"|"Croissance"|"Économie"|"Direction";
export interface StrategyStudyDefinition { id:StrategyStudyId; order:number; title:string; shortTitle:string; pillar:StrategyPillar; purpose:string; inputs:string[]; outputs:string[]; dependsOn:StrategyStudyId[]; icon:string }
export interface StrategyStudyResult { id:string; studyId:StrategyStudyId; caseId:string; title:string; executiveSummary:string; confidence:number; assumptions:string[]; findings:Array<{label:string;value:string}>; recommendations:string[]; nextActions:string[]; createdAt:string }

export const STRATEGY_STUDIES:StrategyStudyDefinition[]=[
 {id:"market",order:1,title:"Dimensionnement de marché & TAM",shortTitle:"TAM · SAM · SOM",pillar:"Marché",icon:"◎",purpose:"Quantifier l’opportunité par approches top-down et bottom-up, avec croissance à cinq ans.",inputs:["Produit et proposition de valeur","Client cible","Zone géographique","Prix ou revenu moyen par client"],outputs:["TAM / SAM / SOM","CAGR à 5 ans","Hypothèses auditables","Scénarios investisseur"],dependsOn:[]},
 {id:"competition",order:2,title:"Paysage concurrentiel",shortTitle:"Concurrence",pillar:"Marché",icon:"◇",purpose:"Cartographier les acteurs directs, indirects, leurs positions et les espaces blancs.",inputs:["Industrie","Positionnement actuel","Concurrents déjà identifiés"],outputs:["Carte prix / valeur","Menaces par acteur","Moats comparés","Espaces blancs"],dependsOn:[]},
 {id:"personas",order:3,title:"Personas & segmentation",shortTitle:"Personas",pillar:"Client",icon:"◉",purpose:"Construire quatre segments décisionnels, leurs besoins, objections et disposition à payer.",inputs:["Produit","Industrie","Acheteurs et utilisateurs connus"],outputs:["4 personas","Segments dimensionnés","Triggers et objections","Matrice de priorité"],dependsOn:["market"]},
 {id:"trends",order:4,title:"Tendances du secteur",shortTitle:"Tendances",pillar:"Marché",icon:"↗",purpose:"Détecter forces macro, signaux émergents, ruptures et implications concrètes.",inputs:["Secteur et marché","Horizon stratégique","Géographies"],outputs:["Radar de tendances","Impact 1–10","Horizon 0–5 ans","Analyse “so what”"],dependsOn:[]},
 {id:"swot",order:5,title:"SWOT & 5 forces de Porter",shortTitle:"SWOT + Porter",pillar:"Direction",icon:"✣",purpose:"Évaluer la position interne et l’attractivité structurelle du secteur.",inputs:["Entreprise et produit","Stade de développement","Marché"],outputs:["SWOT croisée","5 forces notées","Stratégies SO / WT","Score d’attractivité"],dependsOn:["competition","trends"]},
 {id:"pricing",order:6,title:"Stratégie de pricing",shortTitle:"Pricing",pillar:"Économie",icon:"€",purpose:"Fixer le prix plancher, le prix fondé sur la valeur et une architecture de trois offres.",inputs:["Prix actuel","Structure de coûts","Valeur client","Prix concurrents"],outputs:["3 offres et packaging","Élasticité","Politique de remise","3 scénarios de revenus"],dependsOn:["personas","competition"]},
 {id:"gtm",order:7,title:"Stratégie Go-to-Market",shortTitle:"Go-to-Market",pillar:"Croissance",icon:"➜",purpose:"Transformer le positionnement en plan de lancement pilotable sur 60 + 90 jours.",inputs:["Produit et marché","Budget","Timeline","Objectif de traction"],outputs:["Plan 60/7/90 jours","Canaux classés par ROI","Messaging","KPI et responsables"],dependsOn:["personas","pricing"]},
 {id:"journey",order:8,title:"Parcours client",shortTitle:"Customer Journey",pillar:"Client",icon:"⌁",purpose:"Cartographier de la notoriété au churn les frictions, émotions et moments d’activation.",inputs:["Type de client","Canaux actuels","Conversion et rétention"],outputs:["7 étapes du parcours","Courbe émotionnelle","Friction et opportunités","KPI par étape"],dependsOn:["personas"]},
 {id:"economics",order:9,title:"Modèle financier & unit economics",shortTitle:"Unit economics",pillar:"Économie",icon:"∑",purpose:"Modéliser CAC, LTV, marge, payback, trésorerie et seuil de rentabilité sur trois ans.",inputs:["Revenus actuels","Coûts fixes et variables","Croissance","Churn et acquisition"],outputs:["LTV:CAC et payback","P&L 3 ans","Burn et break-even","Sensibilités"],dependsOn:["market","pricing","gtm"]},
 {id:"synthesis",order:10,title:"Synthèse stratégique executive",shortTitle:"Executive synthesis",pillar:"Direction",icon:"✦",purpose:"Arbitrer toutes les analyses en une recommandation, trois options et un plan à 90 jours.",inputs:["Objectifs","Contraintes","Résultats des études","Principal défi"],outputs:["Executive summary","3 trajectoires","Choix recommandé","5 initiatives à 90 jours"],dependsOn:["market","competition","personas","trends","swot","pricing","gtm","journey","economics"]}
];
export function strategyReadiness(study:StrategyStudyDefinition,completed:StrategyStudyId[],context:string){const dependencies=study.dependsOn.filter((id)=>!completed.includes(id));const contextScore=Math.min(35,Math.floor(context.trim().length/18));return {score:Math.min(100,35+contextScore+(study.dependsOn.length-dependencies.length)*15),dependencies,ready:dependencies.length===0&&context.trim().length>=30};}
export function runStrategyStudy(input:{study:StrategyStudyDefinition;cognitiveCase:CognitiveCase;context:string;completed:StrategyStudyId[];createdAt?:string}):StrategyStudyResult{const {study,cognitiveCase}=input;const createdAt=input.createdAt??new Date().toISOString();const readiness=strategyReadiness(study,input.completed,input.context);const confidence=Math.min(92,Math.max(48,readiness.score-4));const assumptions=study.inputs.slice(0,3).map((item,index)=>`${item} : ${index===0?input.context.slice(0,110)||"à confirmer":index===1?"inféré du contexte du dossier":"donnée à valider par une source externe"}`);return {id:crypto.randomUUID(),studyId:study.id,caseId:cognitiveCase.id,title:study.title,executiveSummary:`ORION a structuré ${study.title.toLocaleLowerCase("fr")} pour ${cognitiveCase.title}. La priorité est de transformer les hypothèses sensibles en preuves, puis de relier le résultat à une décision mesurable.`,confidence,assumptions,findings:[{label:"Diagnostic",value:`${study.shortTitle} est appliqué à l’objectif « ${cognitiveCase.objective} ».`},{label:"Signal prioritaire",value:readiness.dependencies.length?`La solidité dépend encore de ${readiness.dependencies.length} analyse(s) amont.`:"Le contexte permet une première recommandation actionnable."},{label:"Qualité de preuve",value:`Confiance ${confidence}% · ${assumptions.length} hypothèses explicites · validation terrain requise avant engagement irréversible.`}],recommendations:[`Valider les deux hypothèses ayant le plus d’impact sur ${cognitiveCase.objective}.`,`Comparer un scénario prudent, central et offensif avec les mêmes métriques.`,`Fixer un signal de révision et un propriétaire avant exécution.`],nextActions:[`Collecter les données manquantes pour ${study.shortTitle}.`,`Faire challenger le résultat par ATHENA et le responsable métier.`,`Transformer la recommandation retenue en décision puis en plan d’action.`],createdAt};}
export function completedStrategyStudies(knowledgeTitles:string[],caseId:string):StrategyStudyId[]{return STRATEGY_STUDIES.filter((study)=>knowledgeTitles.includes(`Strategy Studio · ${caseId} · ${study.id}`)).map((study)=>study.id);}
