"use client";
import {useEffect,useMemo,useState} from "react";
import {buildActivation} from "@/lib/product-activation";
import {useExecutiveStore} from "@/store/executive-store";

type Profile={industry:string;companySize:string;primaryGoal:string;decisionCadence:string;orionTone:string;weeklyBrief:boolean};
const initialProfile:Profile={industry:"",companySize:"1-10",primaryGoal:"",decisionCadence:"weekly",orionTone:"executive",weeklyBrief:true};

export function ProductControlCenter(){
  const store=useExecutiveStore();const organization=store.organizations.find((item)=>item.id===store.activeOrganizationId);const [profile,setProfile]=useState(initialProfile);const [profileState,setProfileState]=useState("Prêt");const [email,setEmail]=useState("");const [role,setRole]=useState("member");const [inviteState,setInviteState]=useState("");
  const activation=useMemo(()=>buildActivation({cases:store.cases.length,sources:store.contextSources.length,orionCycles:store.agentRuns.length,decisions:store.decisions.length,actions:store.actions.length,members:store.organizationMembers.filter((item)=>item.organizationId===store.activeOrganizationId).length,cloudConnected:!store.activeOrganizationId.startsWith("org-")}),[store.cases.length,store.contextSources.length,store.agentRuns.length,store.decisions.length,store.actions.length,store.organizationMembers,store.activeOrganizationId]);
  useEffect(()=>{if(!organization||organization.id.startsWith("org-"))return;fetch(`/api/product/profile?organizationId=${encodeURIComponent(organization.id)}`,{cache:"no-store"}).then((r)=>r.ok?r.json():null).then((body)=>{const p=body?.profile;if(p)setProfile({industry:p.industry??"",companySize:p.company_size??"1-10",primaryGoal:p.primary_goal??"",decisionCadence:p.decision_cadence??"weekly",orionTone:p.orion_tone??"executive",weeklyBrief:Boolean(p.weekly_brief)});}).catch(()=>undefined);},[organization]);
  async function saveProfile(){if(!organization)return;setProfileState("Enregistrement…");const response=await fetch("/api/product/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:organization.id,...profile})});setProfileState(response.ok?"Enregistré dans le cloud":"Mode local");if(response.ok)void track("profile.completed",{activation:activation.proof.activation});}
  async function invite(){if(!organization||!email.trim())return;setInviteState("Envoi…");const response=await fetch("/api/team/invitations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:organization.id,email,role})});if(response.ok){store.inviteMember(email,role as "admin"|"member"|"viewer");setEmail("");setInviteState("Invitation créée");void track("team.invited",{role});}else setInviteState(response.status===409?"Invitation déjà active":"Invitation impossible");}
  function exportWorkspace(){const payload={exportedAt:new Date().toISOString(),version:27,organization,workspace:useExecutiveStore.getState()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const href=URL.createObjectURL(blob);const link=document.createElement("a");link.href=href;link.download=`executiveos-${organization?.slug??"workspace"}.json`;link.click();URL.revokeObjectURL(href);void track("workspace.exported",{cases:store.cases.length});}
  async function track(name:string,properties:Record<string,unknown>){if(!organization)return;await fetch("/api/product/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:organization.id,name,properties})}).catch(()=>undefined);}
  const localBytes=typeof window==="undefined"?0:new Blob([localStorage.getItem("executiveos-v2")??""]).size;
  return <section><header className="mb-7"><div className="text-[10px] font-black uppercase tracking-[.2em] text-[#7c92b2]">Bloc 10 · Productization</div><h1 className="mt-3 text-4xl font-semibold">Centre de contrôle</h1><p className="mt-3 text-lg text-[#91a2bd]">Activation, organisation, équipe, données et preuve de valeur.</p></header>
    <div className="grid gap-5 xl:grid-cols-3">
      <Card title="Activation produit" wide><div className="flex items-end justify-between"><div><strong className="text-5xl">{activation.proof.activation}%</strong><p className="mt-2 text-sm text-[#91a2bd]">{activation.proof.completedSteps}/{activation.proof.totalSteps} jalons atteints</p></div><Badge text={activation.proof.timeToValueReady?"VALEUR PROUVÉE":"EN COURS"}/></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full bg-gradient-to-r from-[#7657ff] to-[#42d59d]" style={{width:`${activation.proof.activation}%`}}/></div><div className="grid gap-2 sm:grid-cols-2">{activation.steps.map((step)=><div key={step.id} className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.025] p-3 text-sm"><span className={step.complete?"text-[#42d59d]":"text-[#52647f]"}>{step.complete?"✓":"○"}</span>{step.label}</div>)}</div></Card>
      <Card title="Preuve de valeur"><Metric label="Dossiers décidés" value={`${activation.proof.decisionCoverage}%`}/><Metric label="Décisions exécutées" value={`${activation.proof.executionCoverage}%`}/><Metric label="Collaboration" value={activation.proof.collaborationReady?"Active":"À activer"}/><Metric label="Cycles Assistant de décision" value={String(store.agentRuns.length)}/></Card>
      <Card title="Profil d’organisation" wide><div className="grid gap-3 sm:grid-cols-2"><Input label="Secteur" value={profile.industry} onChange={(industry)=>setProfile((p)=>({...p,industry}))} placeholder="Défense, SaaS, industrie…"/><Input label="Taille" value={profile.companySize} onChange={(companySize)=>setProfile((p)=>({...p,companySize}))} placeholder="1-10"/><div className="sm:col-span-2"><Input label="Objectif prioritaire" value={profile.primaryGoal} onChange={(primaryGoal)=>setProfile((p)=>({...p,primaryGoal}))} placeholder="La valeur principale attendue d’ExecutiveOS"/></div><Select label="Cadence de décision" value={profile.decisionCadence} onChange={(decisionCadence)=>setProfile((p)=>({...p,decisionCadence}))} options={["daily","weekly","monthly"]}/><Select label="Style Assistant de décision" value={profile.orionTone} onChange={(orionTone)=>setProfile((p)=>({...p,orionTone}))} options={["executive","challenger","coach"]}/></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={profile.weeklyBrief} onChange={(e)=>setProfile((p)=>({...p,weeklyBrief:e.target.checked}))}/> Brief exécutif hebdomadaire</label><button onClick={saveProfile} className="rounded-xl bg-[#7c5cff] px-4 py-3 text-sm font-bold">Enregistrer · {profileState}</button></Card>
      <Card title="Équipe cloud"><div className="grid grid-cols-[1fr_auto] gap-2"><input aria-label="E-mail du collaborateur" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="collaborateur@entreprise.fr" className="min-w-0 rounded-xl border border-white/[.08] bg-white/[.03] px-4 py-3 text-sm outline-none"/><select aria-label="Rôle" value={role} onChange={(e)=>setRole(e.target.value)} className="rounded-xl border border-white/[.08] bg-[#091422] px-3 text-sm"><option value="admin">Admin</option><option value="member">Membre</option><option value="viewer">Lecteur</option></select></div><button onClick={invite} className="w-full rounded-xl bg-[#7c5cff] px-4 py-3 text-sm font-bold">Inviter</button>{inviteState&&<p role="status" className="text-xs text-[#b7a9ff]">{inviteState}</p>}{store.organizationMembers.filter((m)=>m.organizationId===store.activeOrganizationId).map((m)=><Metric key={m.id} label={m.displayName} value={m.role}/>)}</Card>
      <Card title="Données & continuité"><Metric label="Stockage local" value={`${Math.ceil(localBytes/1024)} Ko`}/><Metric label="Dossiers exportables" value={String(store.cases.length)}/><Metric label="Sources traçables" value={String(store.contextSources.length)}/><button onClick={exportWorkspace} className="w-full rounded-xl border border-white/[.1] bg-white/[.04] px-4 py-3 text-left text-sm font-semibold">Exporter tout l’espace en JSON</button><button onClick={()=>window.dispatchEvent(new CustomEvent("executiveos:sync"))} className="w-full rounded-xl border border-white/[.1] bg-white/[.04] px-4 py-3 text-left text-sm font-semibold">Demander une synchronisation cloud</button></Card>
      <Card title="Connecter mes données" wide><p className="text-sm leading-6 text-[#91a2bd]">Préparez l’import automatique du contexte utile à une décision. Aucun accès n’est activé sans votre consentement.</p><div className="grid gap-3 sm:grid-cols-2">{[["Gmail / Outlook","Fils de discussion liés à une décision"],["Google Calendar / Outlook","Réunions, participants et échéances"],["Google Drive","Mémos et documents de travail"],["SharePoint","Documents et dossiers gouvernés"]].map(([name,detail])=><div key={name} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{name}</strong><Badge text="BIENTÔT DISPONIBLE"/></div><p className="mt-2 text-xs leading-5 text-[#91a2bd]">{detail}</p></div>)}</div></Card>
      <Card title="Confidentialité de vos données" wide><p className="text-sm leading-6 text-[#91a2bd]">Vos décisions restent isolées dans votre espace. Les données fictives de démonstration ne sont jamais mélangées à votre doctrine personnelle.</p><div className="grid gap-2 sm:grid-cols-3"><Metric label="Accès" value="Vous et les membres autorisés"/><Metric label="Stockage" value={organization?.id.startsWith("org-") ? "Cet appareil" : "Espace cloud isolé"}/><Metric label="Usage" value="Aucun entraînement partagé"/></div><details className="rounded-xl border border-white/[.08] bg-white/[.025] p-4"><summary className="cursor-pointer text-sm font-semibold">Voir les garanties essentielles</summary><ul className="mt-3 space-y-2 text-xs leading-5 text-[#91a2bd]"><li>• Isolation par organisation et session authentifiée.</li><li>• Exemples fictifs séparés des calculs personnels.</li><li>• Export complet disponible à tout moment.</li><li>• Chaque futur connecteur demandera une autorisation explicite et révocable.</li></ul></details></Card>
      <Card title="Readiness investisseur"><Metric label="Produit" value={activation.proof.activation>=80?"Démontrable":"À compléter"}/><Metric label="Traçabilité" value={store.events.length>0?"Active":"Vide"}/><Metric label="Moteurs cognitifs" value={String(store.agents.filter((a)=>a.status!=="offline").length)}/><Metric label="Portefeuille" value={`${store.projects.length} projets · ${store.ideas.length} idées`}/></Card>
    </div></section>;
}
function Card({title,children,wide=false}:{title:string;children:React.ReactNode;wide?:boolean}){return <article className={`rounded-[26px] border border-white/[.08] bg-[#0d192b]/88 p-5 md:p-6 ${wide?"xl:col-span-2":""}`}><div className="text-[10px] font-black uppercase tracking-[.16em] text-[#9d83ff]">{title}</div><div className="mt-4 space-y-3">{children}</div></article>}
function Metric({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.025] p-3"><span className="text-xs text-[#91a2bd]">{label}</span><strong className="text-sm">{value}</strong></div>}
function Badge({text}:{text:string}){return <span className="rounded-full bg-[#42d59d]/15 px-3 py-1 text-[10px] font-black text-[#79e0ba]">{text}</span>}
function Input({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder:string}){return <label className="grid gap-2 text-xs text-[#91a2bd]">{label}<input value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className="rounded-xl border border-white/[.08] bg-[#091422] px-4 py-3 text-sm text-white outline-none"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="grid gap-2 text-xs text-[#91a2bd]">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-white/[.08] bg-[#091422] px-4 py-3 text-sm text-white">{options.map((o)=><option key={o}>{o}</option>)}</select></label>}
