"use client";
import { useMemo, useState } from "react";
import type { CognitiveCase } from "@/domain/canonical";
import { STRATEGY_STUDIES, completedStrategyStudies, runStrategyStudy, strategyReadiness, type StrategyPillar, type StrategyStudyId, type StrategyStudyResult } from "@/lib/strategy-studio";
import { useExecutiveStore } from "@/store/executive-store";
const PILLARS:Array<"Tout"|StrategyPillar>=["Tout","Marché","Client","Croissance","Économie","Direction"];
export function StrategyStudio({cognitiveCase}:{cognitiveCase:CognitiveCase}){
 const store=useExecutiveStore(); const [pillar,setPillar]=useState<(typeof PILLARS)[number]>("Tout"); const [selected,setSelected]=useState<StrategyStudyId>("market"); const [context,setContext]=useState([cognitiveCase.context,cognitiveCase.workingHypothesis].filter(Boolean).join("\n")); const [results,setResults]=useState<Partial<Record<StrategyStudyId,StrategyStudyResult>>>({}); const [status,setStatus]=useState("");
 const persisted=useMemo(()=>completedStrategyStudies(store.knowledgeRecords.filter((item)=>item.caseId===cognitiveCase.id).map((item)=>item.title),cognitiveCase.id),[store.knowledgeRecords,cognitiveCase.id]); const completed=useMemo(()=>Array.from(new Set([...persisted,...Object.keys(results) as StrategyStudyId[]])),[persisted,results]); const studies=STRATEGY_STUDIES.filter((study)=>pillar==="Tout"||study.pillar===pillar); const active=STRATEGY_STUDIES.find((study)=>study.id===selected)??STRATEGY_STUDIES[0]!; const readiness=strategyReadiness(active,completed,context); const result=results[active.id];
 function run(){if(!readiness.ready){setStatus(readiness.dependencies.length?`Terminez d’abord : ${readiness.dependencies.map((id)=>STRATEGY_STUDIES.find((s)=>s.id===id)?.shortTitle).join(", ")}.`:"Ajoutez quelques lignes de contexte fiable.");return;}const next=runStrategyStudy({study:active,cognitiveCase,context,completed});setResults((current)=>({...current,[active.id]:next}));store.prependKnowledge([{id:crypto.randomUUID(),caseId:cognitiveCase.id,type:"insight",title:`Strategy Studio · ${cognitiveCase.id} · ${active.id}`,confidence:next.confidence,source:"manual",createdAt:next.createdAt}]);store.prependMemories([{id:crypto.randomUUID(),caseId:cognitiveCase.id,kind:"context",content:`${active.title} — ${next.executiveSummary}`,confidence:next.confidence,durable:true,source:"manual",createdAt:next.createdAt}]);setStatus(`${active.shortTitle} terminé et enregistré dans la mémoire vivante.`);}
 function createActions(){if(!result)return;result.nextActions.forEach((title)=>store.createAction({caseId:cognitiveCase.id,title,owner:"Perspective stratégique",requiredCapability:"strategy"}));setStatus("3 actions créées dans le plan d’exécution.");} function createDecision(){if(!result)return;store.captureDecision({caseId:cognitiveCase.id,text:`Valider l’orientation issue de ${active.shortTitle}`,recommendation:result.recommendations[0]!,confidence:result.confidence,rationale:result.executiveSummary});setStatus("Recommandation transformée en décision traçable.");}
 return <section aria-label="Strategy Studio" className="overflow-hidden rounded-[28px] border border-white/[.08] bg-[#0d192b]/88"><header className="border-b border-white/[.08] p-5 md:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="text-[10px] font-black uppercase tracking-[.18em] text-[#a995ff]">Perspective stratégique × Assistant de décision · Strategy Studio</div><h2 className="mt-2 text-3xl font-semibold tracking-[-.035em]">De l’intuition au dossier investissable</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-[#91a2bd]">Dix analyses reliées, avec hypothèses visibles, confiance et conversion en décision ou plan.</p></div><div className="rounded-2xl border border-[#42d59d]/20 bg-[#42d59d]/[.06] px-4 py-3"><strong className="text-2xl text-[#83dfbd]">{completed.length}/10</strong><span className="ml-2 text-xs text-[#91a2bd]">analyses capitalisées</span></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{PILLARS.map((item)=><button key={item} aria-pressed={pillar===item} onClick={()=>setPillar(item)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${pillar===item?"bg-[#7c5cff] text-white":"border border-white/[.08] text-[#91a2bd]"}`}>{item}</button>)}</div></header>
 <div className="grid lg:grid-cols-[360px_minmax(0,1fr)]"><nav aria-label="Analyses stratégiques" className="max-h-[720px] overflow-auto border-b border-white/[.08] p-3 lg:border-b-0 lg:border-r">{studies.map((study)=>{const state=strategyReadiness(study,completed,context);const done=completed.includes(study.id);return <button key={study.id} onClick={()=>setSelected(study.id)} className={`mb-2 flex w-full items-start gap-3 rounded-2xl border p-3.5 text-left ${selected===study.id?"border-[#7c5cff]/45 bg-[#7c5cff]/10":"border-transparent hover:bg-white/[.035]"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-xl ${done?"bg-[#42d59d]/15 text-[#83dfbd]":"bg-white/[.05] text-[#b7a9ff]"}`}>{done?"✓":study.icon}</span><span className="min-w-0 flex-1"><span className="text-[9px] uppercase tracking-[.12em] text-[#667995]">{String(study.order).padStart(2,"0")} · {study.pillar}</span><strong className="mt-1 block text-sm">{study.shortTitle}</strong><span className="mt-1 block text-[10px] text-[#71839e]">{done?"Capitalisée":`${state.score}% prêt`}</span></span></button>})}</nav>
 <div className="p-5 md:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><span className="text-[10px] font-black uppercase tracking-[.14em] text-[#9d83ff]">Analyse {String(active.order).padStart(2,"0")}</span><h3 className="mt-2 text-2xl font-semibold">{active.title}</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#91a2bd]">{active.purpose}</p></div><span className={`shrink-0 rounded-xl border border-white/[.08] px-3 py-2 text-xs ${readiness.ready?"text-[#83dfbd]":"text-[#f4c76d]"}`}>{readiness.score}% prêt</span></div><div className="mt-5 grid gap-4 xl:grid-cols-2"><InfoList title="Données nécessaires" items={active.inputs}/><InfoList title="Livrables produits" items={active.outputs}/></div><label className="mt-5 block"><span className="text-[10px] font-black uppercase tracking-[.12em] text-[#71839e]">Contexte et données disponibles</span><textarea aria-label="Contexte de l’analyse" value={context} onChange={(e)=>setContext(e.target.value)} className="mt-2 min-h-28 w-full rounded-2xl border border-white/[.08] bg-[#07131f] p-4 text-sm leading-6 outline-none focus:border-[#7c5cff]/60" placeholder="Produit, cible, marché, chiffres, contraintes, sources…"/></label>
 {readiness.dependencies.length>0&&<div className="mt-3 rounded-xl border border-[#f4c76d]/20 bg-[#f4c76d]/[.06] p-3 text-xs leading-5 text-[#d8bd86]">Dépendances : {readiness.dependencies.map((id)=>STRATEGY_STUDIES.find((study)=>study.id===id)?.shortTitle).join(" · ")}</div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={run} disabled={!readiness.ready} className="rounded-xl bg-[#7c5cff] px-5 py-3 text-sm font-bold disabled:cursor-not-allowed disabled:opacity-35">{result?"Actualiser l’analyse":"Lancer avec Assistant de décision"}</button>{result&&<><button onClick={createDecision} className="rounded-xl border border-[#f4c76d]/30 bg-[#f4c76d]/10 px-4 py-3 text-sm font-semibold text-[#f4c76d]">Transformer en décision</button><button onClick={createActions} className="rounded-xl border border-[#42d59d]/30 bg-[#42d59d]/10 px-4 py-3 text-sm font-semibold text-[#83dfbd]">Créer le plan d’action</button></>}</div>{status&&<p role="status" className="mt-3 text-xs text-[#83dfbd]">{status}</p>}
 {result&&<article className="mt-6 rounded-[22px] border border-[#7c5cff]/25 bg-[#07131f]/80 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Synthèse Assistant de décision</strong><span className="rounded-full bg-[#42d59d]/10 px-2.5 py-1 text-[10px] text-[#83dfbd]">Confiance {result.confidence}%</span></div><p className="mt-3 text-sm leading-6 text-[#bdc9d9]">{result.executiveSummary}</p><div className="mt-4 space-y-2">{result.findings.map((item)=><div key={item.label} className="rounded-xl border border-white/[.06] bg-white/[.025] p-3"><span className="text-[9px] font-black uppercase text-[#9d83ff]">{item.label}</span><p className="mt-1 text-xs leading-5 text-[#aab7ca]">{item.value}</p></div>)}</div><h4 className="mt-4 text-xs font-black uppercase tracking-[.12em] text-[#71839e]">Recommandations</h4><ul className="mt-2 space-y-2">{result.recommendations.map((item)=><li key={item} className="text-sm leading-6 text-[#c4cfdd]">• {item}</li>)}</ul></article>}</div></div></section>;
}
function InfoList({title,items}:{title:string;items:string[]}){return <div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><span className="text-[10px] font-black uppercase tracking-[.12em] text-[#71839e]">{title}</span><ul className="mt-3 space-y-2">{items.map((item)=><li key={item} className="text-xs leading-5 text-[#aab7ca]">✓ {item}</li>)}</ul></div>}
