import { useEffect, useMemo, useState } from 'react'

const KEY='memoryos.react.v9'
const initial={journeys:[{id:'j1',name:'Construire MemoryOS',clarity:78}],activeJourneyId:'j1',memories:[],decisions:[],reflections:[],chat:[]}
const labels={dashboard:'Command Center',memory:'Memory Engine',graph:'Knowledge Graph',timeline:'Reasoning Timeline',decisions:'Decision Engine',reflection:'Reflection Engine',mentor:'AI Mentor'}

function extract(text){return text.split(/(?<=[.!?])\s+/).filter(Boolean).map((s,i)=>{const l=s.toLowerCase();let type='fact';if(l.includes('?'))type='question';else if(/il faut|doit|décid/.test(l))type='decision';else if(/je pense|probable|peut-être/.test(l))type='hypothesis';else if(/mais|car|parce que/.test(l))type='argument';return{id:Date.now()+i,type,text:s.trim(),approved:true}})}

export default function App(){
  const [state,setState]=useState(()=>{try{return JSON.parse(localStorage.getItem(KEY))||initial}catch{return initial}})
  const [view,setView]=useState('dashboard'),[light,setLight]=useState(false),[text,setText]=useState(''),[items,setItems]=useState([]),[source,setSource]=useState('Réflexion'),[mentorInput,setMentorInput]=useState('')
  useEffect(()=>localStorage.setItem(KEY,JSON.stringify(state)),[state])
  const journey=state.journeys.find(j=>j.id===state.activeJourneyId)
  const memories=state.memories.filter(x=>x.journeyId===state.activeJourneyId)
  const decisions=state.decisions.filter(x=>x.journeyId===state.activeJourneyId)
  const reflections=state.reflections.filter(x=>x.journeyId===state.activeJourneyId)
  const chat=state.chat.filter(x=>x.journeyId===state.activeJourneyId)
  const allItems=useMemo(()=>memories.flatMap(m=>(m.items||[]).map(i=>({...i,date:m.date,source:m.source}))),[memories])

  function addJourney(){const name=prompt('Nom du Journey');if(!name?.trim())return;const id='j'+Date.now();setState(s=>({...s,activeJourneyId:id,journeys:[...s.journeys,{id,name:name.trim(),clarity:10}]}))}
  function saveMemory(){const approved=items.filter(x=>x.approved);if(!approved.length)return alert('Aucun élément validé.');const memory={id:Date.now(),journeyId:state.activeJourneyId,source,text:text.trim(),items:approved,date:new Date().toISOString()};const created=approved.filter(x=>x.type==='decision').map((x,i)=>({id:Date.now()+i,journeyId:state.activeJourneyId,title:x.text,confidence:70,status:'active',reviewTrigger:'Quand une hypothèse clé change'}));setState(s=>({...s,memories:[memory,...s.memories],decisions:[...created,...s.decisions],journeys:s.journeys.map(j=>j.id===s.activeJourneyId?{...j,clarity:Math.min(100,(j.clarity||0)+5)}:j)}));setText('');setItems([])}
  function scan(){const found=[];if(allItems.some(i=>i.type==='decision')&&allItems.some(i=>i.type==='hypothesis'))found.push({id:Date.now(),journeyId:state.activeJourneyId,type:'contradiction',title:'Décision fondée sur une hypothèse à valider',question:'Quelle preuve invaliderait cette hypothèse ?',status:'open'});if(!allItems.some(i=>i.type==='question'))found.push({id:Date.now()+1,journeyId:state.activeJourneyId,type:'blindspot',title:'Aucune question ouverte enregistrée',question:'Quel point essentiel reste incertain ?',status:'open'});if(!found.length)found.push({id:Date.now()+2,journeyId:state.activeJourneyId,type:'question',title:'Mesure de la continuité cognitive',question:'Quel indicateur prouve que l’utilisateur recommence moins ses recherches ?',status:'open'});setState(s=>({...s,reflections:[...found,...s.reflections]}))}
  function send(){const q=mentorInput.trim();if(!q)return;const l=q.toLowerCase(),mem=memories[0],dec=decisions.find(d=>d.status==='review')||decisions[0],ref=reflections.find(r=>r.status!=='resolved');let answer=`Distingue ce que tu sais, ce que tu supposes et ce que tu dois tester sur « ${journey?.name||'ce sujet'} ». `;if(l.includes('où en étais')||l.includes('reprendre'))answer=mem?`Tu en étais ici : ${mem.text}. La prochaine étape logique est de tester l’hypothèse centrale.`:'Aucune mémoire disponible.';else if(l.includes('décision'))answer=dec?`La décision à examiner est « ${dec.title} », avec ${dec.confidence}% de confiance.`:'Aucune décision suivie.';else if(l.includes('angle mort')||l.includes('contradiction'))answer=ref?`Le signal prioritaire est « ${ref.title} ». ${ref.question}`:'Aucun signal ouvert.';setState(s=>({...s,chat:[...s.chat,{id:Date.now(),journeyId:s.activeJourneyId,role:'user',text:q},{id:Date.now()+1,journeyId:s.activeJourneyId,role:'assistant',text:answer}]}));setMentorInput('')}
  function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='memoryos-export.json';a.click();URL.revokeObjectURL(url)}

  const nav=[['dashboard','⌂'],['memory','✦'],['graph','⌘'],['timeline','◷'],['decisions','◇'],['reflection','◉'],['mentor','✺']]
  return <div className={light?'shell light':'shell'}><div className="app">
    <aside className="sidebar"><div className="brand"><div className="logo">M</div><div><strong>MemoryOS</strong><span>Cognitive Operating System</span></div></div><button className="primary full" onClick={()=>setView('memory')}>＋ Nouvelle mémoire</button><nav>{nav.map(([id,icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{icon} {labels[id]}</button>)}</nav><div className="journey-head"><span>JOURNEYS</span><button onClick={addJourney}>＋</button></div>{state.journeys.map(j=><button className={j.id===state.activeJourneyId?'journey active':'journey'} key={j.id} onClick={()=>setState(s=>({...s,activeJourneyId:j.id}))}><span>● {j.name}</span><small>{j.clarity}%</small></button>)}</aside>
    <main><header><div>MemoryOS / <strong>{labels[view]}</strong></div><div className="actions"><span className="chip">● {journey?.name||'Aucun Journey'}</span><button className="ghost" onClick={exportData}>Exporter</button><button className="ghost" onClick={()=>setLight(!light)}>{light?'☀':'☾'}</button></div></header><section className="content">
      {view==='dashboard'&&<><div className="hero"><div><div className="eyebrow">ITÉRATION 9</div><h1>Ton système cognitif structuré.</h1><p>React, composants et état partagé.</p></div><button className="primary" onClick={()=>setView('memory')}>Capturer une réflexion</button></div><article className="card resume"><div className="eyebrow">LÀ OÙ TU EN ÉTAIS</div><h2>{journey?.name}</h2><p>{memories[0]?.text||'Capture une première réflexion pour créer un point de reprise.'}</p><div className="between"><span>Clarté</span><strong>{journey?.clarity||0}%</strong></div><div className="bar"><span style={{width:`${journey?.clarity||0}%`}}/></div></article><div className="metrics">{[['Mémoires',memories.length],['Décisions',decisions.length],['Signaux',reflections.filter(r=>r.status!=='resolved').length],['Questions',allItems.filter(i=>i.type==='question').length]].map(([k,v])=><article className="card metric" key={k}><span>{k}</span><strong>{v}</strong></article>)}</div></>}
      {view==='memory'&&<><Title e="MEMORY ENGINE" h="Transformer une pensée brute." p="Capture, extraction, validation et mémorisation."/><div className="grid2"><article className="card stack"><div className="tabs">{['Réflexion','Réunion','Article','Décision','Expérience'].map(t=><button className={source===t?'active':''} key={t} onClick={()=>setSource(t)}>{t}</button>)}</div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Qu’as-tu compris, décidé, observé ou remis en question ?"/><div className="between"><button className="ghost" onClick={()=>setText("Je pense que MemoryOS doit privilégier l'écran de reprise cognitive. La capture automatique est utile, mais elle doit rester validable. Il faut tester ce parcours avec cinq utilisateurs. Comment mesurer la confiance de l'utilisateur ?")}>Exemple</button><button className="primary" onClick={()=>text.trim().length<20?alert('Ajoute plus de contexte.'):setItems(extract(text.trim()))}>Analyser</button></div></article><article className="card"><div className="list">{items.length?items.map(x=><div className="item" key={x.id}><div className="between"><span className="tag">{x.type.toUpperCase()}</span><button className="ghost" onClick={()=>setItems(items.map(i=>i.id===x.id?{...i,approved:!i.approved}:i))}>{x.approved?'✓':'○'}</button></div><p>{x.text}</p></div>):<div className="empty">Aucun élément.</div>}</div><button className="primary full" onClick={saveMemory}>Mémoriser</button></article></div></>}
      {view==='graph'&&<><Title e="KNOWLEDGE GRAPH" h="Voir les connexions." p="Les éléments du Journey actif deviennent un graphe cognitif."/><article className="card canvas">{allItems.length?allItems.map((it,i)=>{const a=Math.PI*2*i/allItems.length,x=50+36*Math.cos(a),y=50+36*Math.sin(a);return <div className={`node ${it.type}`} key={`${it.id}-${i}`} style={{left:`calc(${x}% - 70px)`,top:`calc(${y}% - 28px)`}}>{it.text.slice(0,55)}</div>}):<div className="empty floating">Aucune donnée.</div>}</article></>}
      {view==='timeline'&&<><Title e="REASONING TIMELINE" h="Rejouer l’évolution de ta pensée." p="Chaque mémoire devient une étape chronologique."/><article className="card timeline">{memories.length?[...memories].sort((a,b)=>new Date(b.date)-new Date(a.date)).map(m=><div className="step" key={m.id}><time>{new Date(m.date).toLocaleDateString('fr-FR')}</time><div className="rail"/><div className="item"><span className="tag">{m.source.toUpperCase()}</span><h4>{m.text.slice(0,110)}</h4><p>{m.items.length} éléments validés</p></div></div>):<div className="empty">Aucune étape.</div>}</article></>}
      {view==='decisions'&&<><Title e="DECISION ENGINE" h="Suivre les décisions." p="Confiance, statut et critères de réévaluation."/><div className="grid2">{decisions.length?decisions.map(d=><article className="card stack" key={d.id}><span className="tag">{d.status.toUpperCase()}</span><h3>{d.title}</h3><label>Confiance : {d.confidence}%</label><input type="range" min="0" max="100" value={d.confidence} onChange={e=>setState(s=>({...s,decisions:s.decisions.map(x=>x.id===d.id?{...x,confidence:Number(e.target.value)}:x)}))}/><select value={d.status} onChange={e=>setState(s=>({...s,decisions:s.decisions.map(x=>x.id===d.id?{...x,status:e.target.value}:x)}))}><option value="active">Active</option><option value="review">À réévaluer</option><option value="closed">Clôturée</option></select></article>):<div className="empty">Aucune décision.</div>}</div></>}
      {view==='reflection'&&<><div className="hero"><div><div className="eyebrow">REFLECTION ENGINE</div><h1>Mettre ta pensée à l’épreuve.</h1><p>Contradictions, angles morts et questions.</p></div><button className="primary" onClick={scan}>Analyser le Journey</button></div><div className="grid2">{reflections.length?reflections.map(r=><article className="card stack" key={r.id}><span className="tag">{r.type.toUpperCase()}</span><h3>{r.title}</h3><p>{r.question}</p><button className="ghost" onClick={()=>setState(s=>({...s,reflections:s.reflections.map(x=>x.id===r.id?{...x,status:x.status==='resolved'?'open':'resolved'}:x)}))}>{r.status==='resolved'?'Rouvrir':'Résoudre'}</button></article>):<div className="empty">Aucun signal.</div>}</div></>}
      {view==='mentor'&&<><Title e="AI MENTOR" h="Continuer le raisonnement." p="Le mentor utilise toutes les données du Journey actif."/><article className="card chat"><div className="messages">{chat.length?chat.map(m=><div className={m.role==='user'?'msg user':'msg'} key={m.id}><div className="bubble">{m.text}</div></div>):<div className="empty">Pose une question.</div>}</div><div className="composer"><textarea value={mentorInput} onChange={e=>setMentorInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><button className="primary" onClick={send}>Envoyer</button></div></article></>}
    </section></main>
  </div></div>
}
function Title({e,h,p}){return <div className="hero"><div><div className="eyebrow">{e}</div><h1>{h}</h1><p>{p}</p></div></div>}
