import test from "node:test";
import assert from "node:assert/strict";
import type { OrganizationMemberRecord } from "../domain/canonical.ts";
import { can, canAccessCase, createAuditLog, unresolvedComments } from "../lib/collaboration.ts";

const member=(role:OrganizationMemberRecord["role"],id=`member-${role}`):OrganizationMemberRecord=>({id,organizationId:"org",userId:id,displayName:role,email:`${role}@demo.test`,role,status:"active",joinedAt:"2026-08-08T08:00:00.000Z"});
test("B9 role matrix protects organization administration",()=>{assert.equal(can(member("owner"),"manage_organization"),true);assert.equal(can(member("admin"),"manage_members"),true);assert.equal(can(member("member"),"manage_members"),false);assert.equal(can(member("viewer"),"edit"),false);});
test("B9 explicit case grants restrict viewers",()=>{const viewer=member("viewer");const grants=[{id:"g",organizationId:"org",caseId:"case-a",memberId:viewer.id,access:"comment" as const,grantedBy:"owner",createdAt:"2026-08-08T08:00:00.000Z"}];assert.equal(canAccessCase({member:viewer,caseId:"case-a",grants,capability:"comment"}),true);assert.equal(canAccessCase({member:viewer,caseId:"case-a",grants,capability:"edit"}),false);});
test("B9 audit and unresolved discussions remain traceable",()=>{const log=createAuditLog({id:"audit-1",createdAt:"2026-08-08T08:00:00.000Z",organizationId:"org",actorMemberId:"owner",action:"comment.created",targetType:"case",targetId:"case-a",caseId:"case-a",summary:"Added",metadata:{}});assert.equal(log.caseId,"case-a");const comments=[{id:"c1",organizationId:"org",caseId:"case-a",targetType:"case" as const,targetId:"case-a",authorMemberId:"owner",body:"Open",mentions:[],createdAt:"2026-08-08T08:00:00.000Z",updatedAt:"2026-08-08T08:00:00.000Z"},{id:"c2",organizationId:"org",caseId:"case-a",targetType:"case" as const,targetId:"case-a",authorMemberId:"owner",body:"Done",mentions:[],resolvedAt:"2026-08-08T09:00:00.000Z",createdAt:"2026-08-08T07:00:00.000Z",updatedAt:"2026-08-08T09:00:00.000Z"}];assert.deepEqual(unresolvedComments(comments,"case-a").map((item)=>item.id),["c1"]);});
