import type { StateCreator } from "zustand";
import { ingestContextSource as processSource, synthesizeCaseContext } from "../lib/context-ingestion.ts";
import { buildSyncRun, normalizeExternalSignal, PROVIDER_CATALOG } from "../lib/integration-fabric.ts";
import { evaluateDecisionWatch } from "../lib/decision-watch.ts";
import type { ContextEvidenceRecord, ContextSourceRecord } from "../domain/canonical.ts";
import type { ExecutiveState, IntegrationFabricSlice } from "./types.ts";

export const createIntegrationFabricSlice:StateCreator<ExecutiveState,[],[],IntegrationFabricSlice>=(set,get)=>({
  integrationConnections:[],integrationSyncRuns:[],
  connectIntegration:(input)=>{const now=new Date().toISOString();const existing=get().integrationConnections.find((item)=>item.provider===input.provider&&item.caseId===input.caseId);if(existing){set((state)=>({integrationConnections:state.integrationConnections.map((item)=>item.id===existing.id?{...item,status:"connected",enabled:true,error:undefined,updatedAt:now}:item)}));return existing.id;}const id=crypto.randomUUID();const meta=PROVIDER_CATALOG[input.provider];set((state)=>({integrationConnections:[{id,provider:input.provider,label:input.label??meta.label,status:"connected",enabled:true,scopes:input.scopes??meta.scopes,caseId:input.caseId,createdAt:now,updatedAt:now},...state.integrationConnections]}));return id;},
  disconnectIntegration:(connectionId)=>set((state)=>({integrationConnections:state.integrationConnections.map((item)=>item.id===connectionId?{...item,status:"disconnected",enabled:false,updatedAt:new Date().toISOString()}:item)})),
  syncIntegration:(connectionId,signals,startedAt=new Date().toISOString())=>{
    const state=get();const connection=state.integrationConnections.find((item)=>item.id===connectionId);if(!connection||connection.status!=="connected"||!connection.enabled)throw new Error("Le connecteur doit être actif avant synchronisation.");
    const existingFingerprints=new Set(state.contextSources.map((item)=>item.origin));const sources:ContextSourceRecord[]=[];const evidence:ContextEvidenceRecord[]=[];const errors:string[]=[];let duplicates=0;
    for(const signal of signals){try{const normalized=normalizeExternalSignal(connection,signal);if(existingFingerprints.has(normalized.fingerprint)){duplicates++;continue;}const result=processSource({caseId:connection.caseId,type:normalized.type,title:normalized.title,origin:normalized.fingerprint,mimeType:normalized.mimeType,content:normalized.content,createdAt:normalized.createdAt},crypto.randomUUID());sources.push(result.source);evidence.push(...result.evidence);existingFingerprints.add(normalized.fingerprint);}catch(error){errors.push(error instanceof Error?error.message:"Signal illisible.");}}
    const completedAt=new Date().toISOString();const run=buildSyncRun({id:crypto.randomUUID(),connection,discovered:signals.length,ingested:sources.length,duplicates,failed:errors.length,sourceIds:sources.map((item)=>item.id),startedAt,completedAt,errors});
    set((current)=>{const contextSources=[...sources,...current.contextSources];const contextEvidence=[...evidence,...current.contextEvidence];const synthesis=synthesizeCaseContext(connection.caseId,contextSources,contextEvidence,completedAt);const watches=current.decisionActionPlans.filter((plan)=>plan.caseId===connection.caseId&&plan.status==="active").flatMap((plan)=>{const decision=current.decisions.find((item)=>item.id===plan.decisionId);return decision?[evaluateDecisionWatch({plan,decision,actions:current.actions,sources:contextSources,evidence:contextEvidence,evaluatedAt:completedAt})]:[];});const watched=new Set(watches.map((item)=>item.planId));return {contextSources,contextEvidence,contextSyntheses:[synthesis,...current.contextSyntheses.filter((item)=>item.caseId!==connection.caseId)],decisionWatches:[...watches,...current.decisionWatches.filter((item)=>!watched.has(item.planId))],integrationSyncRuns:[run,...current.integrationSyncRuns],integrationConnections:current.integrationConnections.map((item)=>item.id===connection.id?{...item,lastSyncAt:completedAt,cursor:run.cursor,error:errors[0],updatedAt:completedAt}:item),caseObjects:[...evidence.slice(0,4).map((item)=>({id:crypto.randomUUID(),caseId:connection.caseId,type:"context" as const,title:item.claim,confidence:item.confidence,status:"active" as const,source:"conversation" as const,referenceId:item.id,createdAt:item.createdAt,updatedAt:item.createdAt})),...current.caseObjects],events:[{id:crypto.randomUUID(),type:"IntegrationSynced",detail:`${connection.provider} · ${connection.caseId} · ${run.ingested} signal(aux)`,createdAt:completedAt},...current.events]};});return run;
  }
});
